# For Ubuntu run as ansible-playbook update-hosts.yaml -b  -i /etc/ansible/jenkins
---
- name: Transfer and execute a script.
  remote_user: 'ubuntu'
  hosts: jenkins
  tasks:
     - name: Transfer the new server ip file
       copy: src=data/server_ip_list dest=/tmp/ mode=0755
     - name: Transfer the new server ip file
       copy: src=jenkins/update-hosts.sh dest=/tmp/ mode=0755
     - name: Execute the script
       command: bash /tmp/update-hosts.sh
