#!/bin/bash

FILE_SERVER=10.240.32.242
# Install pre-requisite packages
#-------------------------------
apt-get update
apt-get install -y libgtk2.0-dev curl libcurl4-gnutls-dev
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
apt-get install -y nodejs

apt-get install -y g++ gcc make bison git flex build-essential binutils-dev libldap2-dev libcppunit-dev libicu-dev
apt-get install -y libxslt1-dev zlib1g-dev libboost-regex-dev libssl-dev libarchive-dev
apt-get install -y python2.7-dev libv8-dev openjdk-7-jdk libapr1-dev libaprutil1-dev
apt-get install -y libhiredis-dev libtbb-dev libnuma-dev libevent-dev libfreetype6-dev pkg-config fop zip
apt-get install -y libsqlite3-dev libtbb-dev libhiredis-dev
apt-get install -y libboost-thread-dev libboost-filesystem-dev libmysqlclient-dev

# Install R
#-------------------------------
apt-get install -y r-base r-cran-rcpp
wget http://${FILE_SERVER}/data3/software/R/RInside_0.2.10.tar.gz 
R CMD INSTALL RInside_0.2.10.tar.gz
rm -rf *.tar.gz

# Add ANTLRA and graphviz
#-----------------------------------------
wget http://${FILE_SERVER}/data3/software/antlr/ANTLR.tar.gz
tar -zxvf ANTLR.tar.gz -C /usr/local/
wget http://${FILE_SERVER}/data3/software/graphviz/graphviz-2.26.3.tar.gz
tar -zxvf graphviz-2.26.3.tar.gz -C /usr/local/src/
rm -rf *.tar.gz

# Configure Jenkins slaves
#-------------------------------
mkdir -p /jenkins/workspace
chown -R ubuntu:ubuntu jenkins

# Install cmake
#------------------------------
wget http://${FILE_SERVER}/data3/software/cmake/cmake-3.5.2-precise-amd64.tar.gz
tar -zxf cmake-3.5.2-precise-amd64.tar.gz
rm -rf  cmake-3.5.2-precise-amd64.tar.gz
cd  cmake-3.5.2-Linux-x86_64
cp -r * /usr/local/
cd ..
rm -rf *.tar.gz

# Update to new GCC to support C++11
#------------------------------------
add-apt-repository ppa:ubuntu-toolchain-r/test
apt-get update
apt-get install -y gcc-4.8 g++-4.8
update-alternatives --remove-all gcc
update-alternatives --remove-all g++
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
update-alternatives --config gcc
update-alternatives --config g++


# In chance Java 1.6 is installed
#------------------------------------
update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java

# Install Couchbase
#------------------------------------
wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-amd64.deb
sudo dpkg -i couchbase-release-1.0-2-amd64.deb
sudo apt-get update
sudo apt-get install -y libcouchbase-dev libcouchbase2-bin build-essential
rm -rf couchbase-release-1.0-2-amd64.deb

# gpg
#------------------------------
su - ubuntu
wget http://${FILE_SERVER}/data3/build/gpg/HPCCSystems.priv
gpg --import HPCCSystems.priv
rm -rf HPCCSystems.priv
exit


exit 0



