#!/bin/bash
FILE_SERVER=10.240.32.242
yum install -y gcc-c++ gcc make binutils-devel openldap-devel libicu-devel
yum install -y libxslt-devel libarchive-devel boost141-devel openssl-devel apr-devel apr-util-devel
yum install -y hiredis-devel numactl-devel libevent-devel apr1-devel aprutil-devel
yum install -y python26-devel.x86_64 sqlite-devel libmemcached-devel memcached-devel tbb-devel redis
yum install -y rpm-build git mysql-devel curl-devel
curl --silent --location https://rpm.nodesource.com/setup | bash -
yum install -y nodejs

yum install -y python26-devel.x86_64 java-1.6.0-openjdk-devel java-1.7.0-openjdk-devel
# Recent Jenkins requires Java 1.7 or later
update-alternatives --set java /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java

yum install -y R-core-devel
wget http://${FILE_SERVER}/data3/software/R/Rcpp_0.12.1.tar.gz
R CMD INSTALL Rcpp_0.12.1.tar.gz
wget http://${FILE_SERVER}/data3/software/R/RInside_0.2.12.tar.gz
R CMD INSTALL RInside_0.2.12.tar.gz
rm -rf R*.tar.gz

wget http://${FILE_SERVER}/data3/software/antlr/ANTLR.tar.gz
tar -zxvf ANTLR.tar.gz -C /usr/local/
rm -rf ANTLR.tar.gz
wget http://${FILE_SERVER}/data3/software/graphviz/graphviz-2.26.3.tar.gz
tar -zxvf graphviz-2.26.3.tar.gz -C /usr/local/src/
rm -rf graphviz-2.26.3.tar.gz

mkdir -p /jenkins/workspace
chown -R centos:centos /jenkins

expected_version=3.5.2
wget http://${FILE_SERVER}/data3/software/cmake/cmake-${expected_version}-el5-x86_64.tar.gz
tar -zxf cmake-${expected_version}-el5-x86_64.tar.gz
rm -rf  cmake-${expected_version}-el5-x86_64.tar.gz
cd  cmake-${expected_version}-Linux-x86_64
cp -r * /usr/local/
cd 

# Install C++11 package
#------------------------------
wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
yum install -y devtoolset-2-gcc devtoolset-2-binutils
yum install -y devtoolset-2-gcc-gfortran devtoolset-2-gcc-c++
yum install -y devtoolset-2-libatomic-devel devtoolset-2-gdb devtoolset-2-git devtoolset-2-gitk
yum install -y  devtoolset-2-valgrind devtoolset-2-elfutils devtoolset-2-strace devtoolset-2-git-gui

wget http://${FILE_SERVER}/data3/software/bison/bison-2.4.1-src.tar.gz
tar -zxf bison-2.4.1-src.tar.gz
cd bison-2.4.1-src
./configure
make
make install
cd

wget http://${FILE_SERVER}/data3/software/flex/flex-2.5.35.tar.gz
tar -zxf flex-2.5.35.tar.gz
cd flex-2.5.35
./configure
make
make install
cd

wget http://${FILE_SERVER}/data3/software/tbb/tbb-2.2-2.20090809.el5.x86_64.rpm
wget http://${FILE_SERVER}/data3/software/tbb/tbb-devel-2.2-2.20090809.el5.x86_64.rpm
rpm -i tbb-2.2-2.20090809.el5.x86_64.rpm tbb-devel-2.2-2.20090809.el5.x86_64.rpm

# gpg
#------------------------------
su - centos
wget http://${FILE_SERVER}/data3/build/gpg/HPCCSystems.priv
gpg --import HPCCSystems.priv
rm -rf HPCCSystems.priv
exit

